# Documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: Schedulex

options:
  minimumXcodeGenVersion: 2.24
  bundleIdPrefix: sebastian-staszczyk
  groupSortPosition: bottom
  platform: iOS
  deploymentTarget:
    iOS: 16.0

settingGroups:
  common:
    PRODUCT_NAME: UEK Schedule
    MARKETING_VERSION: 1.0.7
    TARGETED_DEVICE_FAMILY: 1

targets:
  Schedulex:
    info:
      path: Schedulex/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    scheme:
      testTargets:
        - name: SchedulexTests
          parallelizable: true
      gatherCoverageData: true
    templates:
      - Schedulex
    dependencies:
      - package: Domain
      - package: Widgets
      - package: Resources
      - package: SchedulexFirebase
      - package: UEKScraper
      - package: SwiftSoup
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift

  SchedulexTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SchedulexTests
    scheme:
      testTargets:
        - SchedulexTests
      gatherCoverageData: true
    settings:
      INFOPLIST_FILE: Schedulex/Info.plist
    dependencies:
      - target: Schedulex
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift

targetTemplates:
  Schedulex:
    platform: iOS
    type: application
    sources: [Schedulex]
    settings:
      groups:
        - common

localPackages:
  - ./Packages/Domain
  - ./Packages/Widgets
  - ./Packages/Resources
  - ./Packages/SchedulexFirebase
  - ./Packages/UEKScraper

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup
    from: 2.6.0
