# Documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: Schedulex

options:
  minimumXcodeGenVersion: 2.24
  bundleIdPrefix: sebastian-staszczyk
  groupSortPosition: bottom
  deploymentTarget:
    iOS: 16.0

settingGroups:
  common:
    PRODUCT_NAME: UEK Schedule
    MARKETING_VERSION: 1.0.26
    TARGETED_DEVICE_FAMILY: 1
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 7TDCFNV5T6

targets:
  Schedulex:
    info:
      path: Schedulex/Info.plist
    scheme:
      testTargets:
        - name: SchedulexTests
          parallelizable: true
    templates:
      - SchedulexApp
    dependencies:
      - package: Domain
      - package: Widgets
      - package: Resources
      - package: SchedulexFirebase
      - package: UEKScraper
      - package: SchedulexCore
      - package: SchedulexViewModel
      - package: SwiftSoup
      - package: Firebase
        products:
          - FirebaseAuth
          - FirebaseFirestore
          - FirebaseFirestoreSwift

  SchedulexTests:
    templates:
      - CommonTest
    dependencies:
      - target: Schedulex

targetTemplates:
  SchedulexApp:
    platform: iOS
    type: application
    sources: [Schedulex]
    settings:
      groups:
        - common
    info:
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        LSApplicationQueriesSchemes:
          - googlegmail
          - ms-outlook
          - readdle-spark
          - ymail
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSApplicationCategoryType: public.app-category.education
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneConfigurationName: Default Configuration

  CommonTest:
    type: bundle.unit-test
    platform: iOS
    sources: [SchedulexTests]
    scheme:
      testTargets:
        - SchedulexTests
      gatherCoverageData: true
    settings:
      INFOPLIST_FILE: Schedulex/Info.plist

localPackages:
  - ./Packages/Domain
  - ./Packages/Widgets
  - ./Packages/Resources
  - ./Packages/SchedulexFirebase
  - ./Packages/UEKScraper
  - ./Packages/SchedulexViewModel
  - ./Packages/SchedulexCore

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup
    from: 2.6.0
